# Generated by Django 4.2.7 on 2023-11-12 15:19

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='questionlikes',
            trigger=pgtrigger.compiler.Trigger(name='question_likes_update', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE ask_me_question\n            SET likes = likes + 1\n            WHERE id = NEW.question_id;\n        ', hash='01c5c39a05167e922f925aee87c98d9f69f5cb49', level='STATEMENT', operation='INSERT', pgid='pgtrigger_question_likes_update_5d969', table='ask_me_questionlikes', when='AFTER')),
        ),
    ]
