# Generated by Django 4.2.7 on 2023-11-12 18:36

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0005_remove_questionlikes_question_likes_update_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='answerlikes',
            trigger=pgtrigger.compiler.Trigger(name='answer_likes_update', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE ask_me_answer\n            SET likes = likes + 1\n            WHERE id = NEW.answer_id;\n            RETURN NEW;\n        ', hash='b686e63c6f54a08f0fa8dcb7ce5a45ac9598a356', operation='INSERT', pgid='pgtrigger_answer_likes_update_3866e', table='ask_me_answerlikes', when='BEFORE')),
        ),
    ]
